export const fullStar = require('../assets/images/full_star.png')
export const halfStar = require('../assets/images/half_star.png')
export const emptyStar = require('../assets/images/empty_star.png')
export const fullHeart = require('../assets/images/full_heart.png')
export const emptyHeart = require('../assets/images/empty_heart.png')
export const logo = require('../assets/images/logo.png')
export const loginBackground = require('../assets/images/login_bg.png')
export const iconCheck = require('../assets/images/icon_check.png')